name: Docker Build
description: Build and push Docker images to Azure Container Registry
inputs:
    DOCKER_REPO:
      description: 'Docker repository'
      required: true
    DOCKER_FILE:
      description: 'Dockerfile path'
      required: true
    BUILD_ARGS:
      description: 'Build arguments'
      required: false
runs:
  using: composite
  steps:
  - name: Build container image and push to Azure
    uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # v6.4.1
    with:
      file: ${{ inputs.DOCKER_FILE }}
      tags: ${{ inputs.DOCKER_REPO }}:latest
      build-args: ${{ inputs.BUILD_ARGS }}
      push: true
