name: Docker Build
description: Build and push Docker images to Azure Container Registry
inputs:
    DOCKER_REPO:
      description: 'Docker repository'
      required: true
    DOCKER_FILE:
      description: 'Dockerfile path'
      required: true
    BUILD_ARGS:
      description: 'Build arguments'
      required: false
runs:
  using: composite
  steps:
  - name: Build container image and push to Azure
    uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6.2.0
    with:
      file: ${{ inputs.DOCKER_FILE }}
      tags: ${{ inputs.DOCKER_REPO }}:latest
      build-args: ${{ inputs.BUILD_ARGS }}
      push: true
