name: CI

on:
  pull_request:
    branches: [ main, production ]
  push:
    branches: [ main, production ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ecosystem: [adoptium, adoptopenjdk]

    steps:
    - name: Setup mvnw arguments
      run: |
        case ${{ matrix.ecosystem }} in
          adoptium) echo "ARGS=-Padoptium,-adoptopenjdk" >> $GITHUB_ENV ;;
          adoptopenjdk) echo "ARGS=-Padoptopenjdk,-adoptium" >> $GITHUB_ENV ;;
        esac

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        persist-credentials: false

    - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build app
      run: ./mvnw --batch-mode clean install ${{ env.ARGS }}
