name: Publish Assets

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # for Git to git push

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build app
        run: ./mvnw --batch-mode clean deploy

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Publish maven assets
        run: |
          ls
          rsync -r ./*/target/mvn-repo ./target/mvn-repo /tmp/
          git checkout --orphan maven || git checkout maven
          git reset .
          rm -r mvn-repo || true
          cp -r /tmp/mvn-repo ./
          ls
          git add mvn-repo
          git commit -a -m "add artifacts"
          git push origin maven
